/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg1_sockets;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.*;
import java.net.*;
import java.io.PrintWriter;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author adhitnugrah
 */
public class A_Chat_Client_GUI extends javax.swing.JFrame 
{
    private static A_Chat_Client ChatClient;
    public static String UserName = "chopper";
    
            /**
     * Creates new form A_Chat_Client_GUI
     */
    public A_Chat_Client_GUI() {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        
        setLocation((screenSize.width - frameSize.width)/2, (screenSize.height - frameSize.height)/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_DISCONNECT = new javax.swing.JButton();
        B_CONNECT = new javax.swing.JButton();
        B_SEND = new javax.swing.JButton();
        B_ABOUT = new javax.swing.JButton();
        B_HELP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TF_MESSAGE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        L_LoggedInAs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA_CONVERSATION = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_ONLINE = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        B_DISCONNECT.setText("Disconnect");
        B_DISCONNECT.setEnabled(false);
        B_DISCONNECT.setName(""); // NOI18N
        B_DISCONNECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DISCONNECTActionPerformed(evt);
            }
        });

        B_CONNECT.setText("Connect");
        B_CONNECT.setPreferredSize(new java.awt.Dimension(85, 23));
        B_CONNECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CONNECTActionPerformed(evt);
            }
        });

        B_SEND.setText("Send");
        B_SEND.setEnabled(false);
        B_SEND.setPreferredSize(new java.awt.Dimension(85, 23));
        B_SEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SENDActionPerformed(evt);
            }
        });

        B_ABOUT.setText("About");
        B_ABOUT.setPreferredSize(new java.awt.Dimension(85, 23));
        B_ABOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ABOUTActionPerformed(evt);
            }
        });

        B_HELP.setText("Help");
        B_HELP.setPreferredSize(new java.awt.Dimension(85, 23));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Message :");
        jLabel1.setToolTipText("");

        TF_MESSAGE.setPreferredSize(new java.awt.Dimension(6, 30));

        jLabel2.setText("Currently Logged In As");

        L_LoggedInAs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Conversation");

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        TA_CONVERSATION.setEditable(false);
        TA_CONVERSATION.setColumns(20);
        TA_CONVERSATION.setLineWrap(true);
        TA_CONVERSATION.setRows(5);
        jScrollPane3.setViewportView(TA_CONVERSATION);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Currently Online");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jScrollPane1.setViewportView(JL_ONLINE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_DISCONNECT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_CONNECT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_SEND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_ABOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_HELP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_MESSAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(L_LoggedInAs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L_LoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_MESSAGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_DISCONNECT)
                    .addComponent(B_CONNECT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_SEND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_ABOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_HELP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CONNECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CONNECTActionPerformed
       BuildLogInWindows();
    }//GEN-LAST:event_B_CONNECTActionPerformed

    private void B_SENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SENDActionPerformed
        if(!TF_MESSAGE.getText().equals(""))
        {
            ChatClient.SEND(TF_MESSAGE.getText());
            TF_MESSAGE.requestFocus();
        }
    }//GEN-LAST:event_B_SENDActionPerformed

    private void B_DISCONNECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DISCONNECTActionPerformed
        try
        {
            ChatClient.DISCONNECT();
        }
        catch(Exception Y)
        {
            Y.printStackTrace();
        }
    }//GEN-LAST:event_B_DISCONNECTActionPerformed

    private void B_ABOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ABOUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_ABOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Chat_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Chat_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Chat_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Chat_Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Chat_Client_GUI().setVisible(true);
            }
        });
    }
    
    public void Connect()
    {
        try
        {
            final int PORT = 444;
            final String HOST = "localhost";
            Socket SOCK = new Socket(HOST, PORT);
            System.out.println("You Connected to : "+HOST);
            
            ChatClient = new A_Chat_Client(SOCK);
            
            PrintWriter OUT = new PrintWriter(SOCK.getOutputStream());
            OUT.println(UserName);
            OUT.flush();
            
            Thread X = new Thread(ChatClient);
            X.start();
        }
        catch(Exception X)
        {
            System.out.println(X);
            JOptionPane.showMessageDialog(null,"server not responding.");
            System.exit(0);
        }
    }
    
    //---------------------------------------------------------
    public void BuildLogInWindows()
    {
        LogInWindows.setTitle("What's your name");
        LogInWindows.setSize(400,100);
        LogInWindows.setResizable(false);
        P_LogIn = new JPanel();
        P_LogIn.add(L_EnterUserName);
        P_LogIn.add(TF_UserNameBox);
        P_LogIn.add(B_Enter);
        LogInWindows.add(P_LogIn);
        Dimension screenSizeL = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSizeL = LogInWindows.getSize();
        LogInWindows.setLocation((screenSizeL.width - frameSizeL.width)/2, (screenSizeL.height - frameSizeL.height)/2);
       
        Login_Action();
        LogInWindows.setVisible(true);
    }
    
    public void Login_Action()
    {
        B_Enter.addActionListener(
                new java.awt.event.ActionListener() 
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        ACTION_B_ENTER();
                    }
                }
            );
    }
    
    public void ACTION_B_ENTER()
    {
        if(!TF_UserNameBox.getText().equals(""))
        {
            UserName = TF_UserNameBox.getText().trim();
            L_LoggedInAs.setText(UserName);
            A_Chat_Server.CurrentUser.add(UserName);
            LogInWindows.setVisible(false);
            B_SEND.setEnabled(true);
            B_DISCONNECT.setEnabled(true);
            B_CONNECT.setEnabled(false);
            Connect();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter your name.");
        }
    }
    //-----------------------------------------------------------------------
    
    //------------------------------------------------------------------
    public static JFrame LogInWindows = new JFrame();
    public static JTextField TF_UserNameBox = new JTextField(20);
    private static JButton B_Enter = new JButton("Enter");
    private static JLabel L_EnterUserName = new JLabel("Enter username : ");
    private static JPanel P_LogIn = new JPanel();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_ABOUT;
    private javax.swing.JButton B_CONNECT;
    private javax.swing.JButton B_DISCONNECT;
    private javax.swing.JButton B_HELP;
    private javax.swing.JButton B_SEND;
    public static javax.swing.JList JL_ONLINE;
    private javax.swing.JLabel L_LoggedInAs;
    public static javax.swing.JTextArea TA_CONVERSATION;
    public static javax.swing.JTextField TF_MESSAGE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
